FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libpq-dev \
    && docker-php-ext-install \
    pgsql \
    pdo_pgsql \
    soap \
    && rm -rf /var/lib/apt/lists/*
